-- Generated by scripts/generate-challenge-seed.mjs — do not edit by hand.
-- Source of truth: content/challenges/**. Regenerate after content changes.

insert into public.challenges (slug, title, tagline, start_date, nights, price_display, is_published)
values ('navratri-2026', 'Navratri: Nine Nights', 'Nine devi forms, one short session each night, everyone moving together. Shailaputri to Siddhidatri, 11–19 October.', '2026-10-11', 9, '', false)
on conflict (slug) do update set
  title = excluded.title, tagline = excluded.tagline, start_date = excluded.start_date,
  nights = excluded.nights, price_display = excluded.price_display, is_published = excluded.is_published;

-- Down:
--   delete from public.challenge_sessions;
--   delete from public.challenges;
