-- 20260806200000_app_authored_catalog.sql
-- Generated from the original, app-authored catalog.
--
-- This content contains no scripture quotations or licensed source text.
-- Source-linked material must still pass the source-rights gate and be
-- ingested through packages/content-tools; this migration is only for
-- curated educational/app-authored content served without the LLM.

-- ---------------------------------------------------------------------------
-- concepts (50)
-- ---------------------------------------------------------------------------
insert into public.concepts (id, slug, term, term_sanskrit, short_definition, full_explanation, examples, related_concepts, tradition_variations) values
  ('00000000-0000-0000-0000-000000000701', 'dharma', 'Dharma', 'धर्म', 'A layered idea involving duty, ethics, right conduct, order, and the way of living that sustains life.', 'Dharma does not have one English equivalent. Its meaning changes with context: it can point to moral responsibility, the nature of a thing, social and personal duty, teaching, or the sustaining order of life.', 'A layered idea involving duty, ethics, right conduct, order, and the way of living that sustains life.', '{}'::text[], '{"note":"Different philosophical schools, texts, communities, and modern teachers emphasise different dimensions of dharma."}'::jsonb),
  ('00000000-0000-0000-0000-000000000702', 'karma', 'Karma', 'कर्म', 'Action and its consequences—not a simple system of instant reward and punishment.', 'Karma literally relates to action. Hindu traditions explore how intention, action, habit, and consequence shape experience across time. It is usually more nuanced than the popular phrase “what goes around comes around.”', 'Action and its consequences—not a simple system of instant reward and punishment.', '{}'::text[], '{"note":"Accounts of how karma operates differ across Hindu philosophies and are also distinct in Buddhist and Jain traditions."}'::jsonb),
  ('00000000-0000-0000-0000-000000000703', 'bhakti', 'Bhakti', 'भक्ति', 'A path and disposition of loving devotion toward the divine.', 'Bhakti can be expressed through remembrance, song, prayer, ritual, service, storytelling, and a personal relationship with a chosen form of the divine.', 'A path and disposition of loving devotion toward the divine.', '{}'::text[], '{"note":"Bhakti traditions differ greatly in theology, deity focus, poetry, ritual, and the relationship they describe between devotee and divine."}'::jsonb),
  ('00000000-0000-0000-0000-000000000704', 'seva', 'Seva', 'सेवा', 'Service offered with care, often without seeking personal reward.', 'Seva can be an everyday ethical practice, community work, temple service, care for family, or service offered as spiritual discipline.', 'Service offered with care, often without seeking personal reward.', '{}'::text[], '{"note":"What counts as seva and how it relates to devotion, duty, and community differs across traditions and contexts."}'::jsonb),
  ('00000000-0000-0000-0000-000000000705', 'atman', 'Atman', 'आत्मन्', 'A word used for self or inner self, with meanings that differ across Hindu philosophies.', 'Atman can refer to the self understood beyond changing roles and moods. Some Vedanta traditions identify atman with ultimate reality, while other Hindu philosophies describe the relationship differently.', 'A word used for self or inner self, with meanings that differ across Hindu philosophies.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000706', 'brahman', 'Brahman', 'ब्रह्मन्', 'A term for ultimate reality or the absolute in several Hindu philosophical traditions.', 'Brahman is not simply a personal deity or a creator figure in every usage. Philosophical schools differ in how they describe its relationship to the world, individual self, and divine forms.', 'A term for ultimate reality or the absolute in several Hindu philosophical traditions.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000707', 'moksha', 'Moksha', 'मोक्ष', 'Liberation or freedom from the limitations described by a tradition’s account of rebirth and suffering.', 'Moksha is described through knowledge, devotion, disciplined practice, divine grace, or combinations of these. It is a spiritual aim rather than a promise of a particular emotional state.', 'Liberation or freedom from the limitations described by a tradition’s account of rebirth and suffering.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000708', 'ahimsa', 'Ahimsa', 'अहिंसा', 'A commitment to reducing harm in thought, speech, and action.', 'Ahimsa is often translated as non-violence, but many teachers also discuss care, restraint, courage, and the complexity of competing responsibilities. It does not require ignoring harm or abandoning boundaries.', 'A commitment to reducing harm in thought, speech, and action.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000709', 'satya', 'Satya', 'सत्य', 'Truthfulness practiced with care for the effects of one’s words.', 'Satya is more than saying everything one thinks. In many ethical discussions, truthfulness is held together with non-harm, discernment, responsibility, and appropriate timing.', 'Truthfulness practiced with care for the effects of one’s words.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000710', 'asteya', 'Asteya', 'अस्तेय', 'A practice of not taking what has not been freely given.', 'Asteya can include respect for another person’s possessions, time, labour, attention, and ideas. It invites honest attention to entitlement and reciprocity.', 'A practice of not taking what has not been freely given.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000711', 'aparigraha', 'Aparigraha', 'अपरिग्रह', 'A practice of loosening possessiveness and unnecessary accumulation.', 'Aparigraha can be explored through simplicity, gratitude, sharing, and noticing the difference between a genuine need and a habit of grasping. It is not a command to neglect safety or material needs.', 'A practice of loosening possessiveness and unnecessary accumulation.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000712', 'santosha', 'Santosha', 'संतोष', 'Contentment: meeting the present without making desire the measure of one’s worth.', 'Santosha does not mean passivity or approval of injustice. It can be a practice of recognising what is present while still taking wise action toward change.', 'Contentment: meeting the present without making desire the measure of one’s worth.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000713', 'tapas', 'Tapas', 'तपस्', 'Disciplined effort or inner heat directed toward transformation.', 'Tapas may describe steady practice, restraint, study, or the willingness to remain present with difficulty. Harmful self-punishment is not a safe substitute for disciplined care.', 'Disciplined effort or inner heat directed toward transformation.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000714', 'svadhyaya', 'Svadhyaya', 'स्वाध्याय', 'Self-study and study of teachings that helps a person see more clearly.', 'Svadhyaya can include reading, recitation, reflection, and observing one’s own patterns. The text and method depend on the lineage or teacher guiding the practice.', 'Self-study and study of teachings that helps a person see more clearly.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000715', 'ishvara', 'Ishvara', 'ईश्वर', 'A word for the Lord or a special divine principle, interpreted differently across schools.', 'In Yoga philosophy, Vedanta, and devotional traditions, Ishvara can carry distinct meanings. It should not be treated as a single universal definition across all Hindu thought.', 'A word for the Lord or a special divine principle, interpreted differently across schools.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000716', 'yoga', 'Yoga', 'योग', 'A broad family of disciplines concerned with steadiness, insight, relationship, and freedom.', 'Yoga includes philosophical, devotional, meditative, ethical, and physical traditions. Modern exercise-based usage is only one part of a much wider history.', 'A broad family of disciplines concerned with steadiness, insight, relationship, and freedom.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000717', 'jnana', 'Jnana', 'ज्ञान', 'Knowledge or insight pursued as a path of spiritual understanding.', 'Jnana is not merely collecting information. In many traditions it includes discernment, inquiry into the self, and a transformation in how reality is understood.', 'Knowledge or insight pursued as a path of spiritual understanding.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000718', 'raja-yoga', 'Raja Yoga', 'राजयोग', 'A name used for contemplative and meditative disciplines, especially in modern presentations of Yoga.', 'The phrase has been used in different historical contexts. Ask which teacher, text, or lineage is being referenced before assuming one fixed method.', 'A name used for contemplative and meditative disciplines, especially in modern presentations of Yoga.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000719', 'karma-yoga', 'Karma Yoga', 'कर्मयोग', 'A path of dedicated action practiced without clinging to personal reward.', 'Karma Yoga does not mean working without rest or accepting exploitation. It asks how intention, responsibility, skill, and attachment shape action.', 'A path of dedicated action practiced without clinging to personal reward.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000720', 'punya', 'Punya', 'पुण्य', 'A term for meritorious or beneficial action in several Hindu accounts of karma.', 'Punya is discussed in relation to generosity, duty, ritual, intention, and their consequences. Different traditions disagree about how merit operates and how it relates to liberation.', 'A term for meritorious or beneficial action in several Hindu accounts of karma.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000721', 'papa', 'Papa', 'पाप', 'A term associated with harmful, wrongful, or demeritorious action in some Hindu frameworks.', 'Papa should not be reduced to a system of shame or instant punishment. Traditions discuss intention, context, repair, consequence, and the possibility of transformation in different ways.', 'A term associated with harmful, wrongful, or demeritorious action in some Hindu frameworks.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000722', 'samsara', 'Samsara', 'संसार', 'The continuing cycle of birth, death, and rebirth described in many Hindu traditions.', 'Samsara is also used to describe a pattern of repetitive attachment and suffering in a person’s lived experience. Its metaphysical meaning and proposed freedom from it vary by school.', 'The continuing cycle of birth, death, and rebirth described in many Hindu traditions.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000723', 'maya', 'Maya', 'माया', 'A term whose meanings include power, appearance, creative force, or mistaken perception.', 'Maya is often mistranslated as simply illusion. Advaita Vedanta, devotional traditions, and other schools use the word with different philosophical emphases.', 'A term whose meanings include power, appearance, creative force, or mistaken perception.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000724', 'guna', 'Guna', 'गुण', 'A quality or strand of nature used in several Hindu philosophical models.', 'The three gunas—sattva, rajas, and tamas—are used to discuss tendencies in mind and matter. They are a contemplative framework, not a medical diagnosis or fixed personality label.', 'A quality or strand of nature used in several Hindu philosophical models.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000725', 'sattva', 'Sattva', 'सत्त्व', 'A quality associated with clarity, balance, harmony, and understanding.', 'Sattva is one of the three gunas. Even positive qualities can become objects of attachment, and the framework should not be used to rank people or communities.', 'A quality associated with clarity, balance, harmony, and understanding.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000726', 'rajas', 'Rajas', 'रजस्', 'A quality associated with activity, movement, desire, and intensity.', 'Rajas can support energy and purposeful work as well as restlessness and grasping. The guna model invites observation rather than moral labelling.', 'A quality associated with activity, movement, desire, and intensity.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000727', 'tamas', 'Tamas', 'तमस्', 'A quality associated with inertia, heaviness, concealment, and stillness.', 'Tamas can describe dullness or confusion in some contexts, but rest and stillness are not inherently wrong. The term should not be used to stigmatise illness, disability, or people.', 'A quality associated with inertia, heaviness, concealment, and stillness.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000728', 'prana', 'Prana', 'प्राण', 'Life-breath or vital energy in several Indian philosophical and practice traditions.', 'Prana is a traditional concept, not a replacement for anatomy or medical care. Breath practices should be gentle and adapted to a person’s circumstances.', 'Life-breath or vital energy in several Indian philosophical and practice traditions.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000729', 'dhyana', 'Dhyana', 'ध्यान', 'Meditative contemplation or sustained attention.', 'Dhyana can refer to different forms of meditation across Yoga, Vedanta, Buddhist, and devotional contexts. A short attention exercise is only an introduction, not a complete lineage practice.', 'Meditative contemplation or sustained attention.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000730', 'dharana', 'Dharana', 'धारणा', 'The practice of gathering attention around a chosen object or focus.', 'Dharana is often described as a stage of concentration in classical Yoga. Teachers differ in the objects, duration, and preparation they recommend.', 'The practice of gathering attention around a chosen object or focus.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000731', 'samadhi', 'Samadhi', 'समाधि', 'A name for profound meditative absorption or integration.', 'Samadhi is described in multiple ways across Yoga and Vedanta traditions. It should not be promised as a quick result of an app exercise or treated as a performance target.', 'A name for profound meditative absorption or integration.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000732', 'puja', 'Puja', 'पूजा', 'A form of worship or respectful offering practiced in many Hindu homes and temples.', 'Puja may include images, offerings, prayer, mantra, light, food, and gestures of welcome. Details differ by deity, region, family, temple, and lineage.', 'A form of worship or respectful offering practiced in many Hindu homes and temples.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000733', 'mantra', 'Mantra', 'मन्त्र', 'A sacred sound, phrase, or formula used in recitation and practice.', 'Mantras may be connected to a deity, teaching, initiation, or ritual. Pronunciation, eligibility, meaning, and method are tradition-specific; a generic app should not impersonate a teacher.', 'A sacred sound, phrase, or formula used in recitation and practice.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000734', 'japa', 'Japa', 'जप', 'Repeated recitation of a mantra, name, or sacred phrase.', 'Japa can be vocal, whispered, or mental and may use counting beads. Counting customs and the choice of mantra should follow a person’s family, teacher, or tradition where applicable.', 'Repeated recitation of a mantra, name, or sacred phrase.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000735', 'murti', 'Murti', 'मूर्ति', 'A consecrated or devotional form through which a deity may be approached.', 'Theological accounts of a murti differ, including whether it is understood as a representation, presence, embodiment, or focus of worship. It should not be dismissed as merely decorative.', 'A consecrated or devotional form through which a deity may be approached.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000736', 'darshan', 'Darshan', 'दर्शन', 'Seeing and being seen by a deity, teacher, or sacred presence.', 'Darshan can refer to temple worship, a teacher’s presence, a philosophical viewpoint, or a moment of insight depending on context. Ask which usage is intended.', 'Seeing and being seen by a deity, teacher, or sacred presence.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000737', 'prasad', 'Prasad', 'प्रसाद', 'Food or an offering received as a gracious return after worship.', 'Prasad may be shared in homes, temples, and festivals. Ingredients, preparation, dietary rules, and the meaning of receiving it vary among communities.', 'Food or an offering received as a gracious return after worship.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000738', 'yajna', 'Yajna', 'यज्ञ', 'A sacrificial or offering rite, with meanings that developed across Vedic and later traditions.', 'Yajna can refer to fire rituals, offerings, duty, generosity, or symbolic self-giving. Ritual performance requires lineage-specific instruction and safety care.', 'A sacrificial or offering rite, with meanings that developed across Vedic and later traditions.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000739', 'tirtha', 'Tirtha', 'तीर्थ', 'A sacred crossing-place, pilgrimage site, or spiritual passage.', 'Tirtha can describe a river, temple, pilgrimage town, teaching, or the act of crossing from confusion toward insight. The places considered sacred differ widely across traditions.', 'A sacred crossing-place, pilgrimage site, or spiritual passage.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000740', 'ashrama', 'Ashrama', 'आश्रम', 'A stage of life, a hermitage, or a community of spiritual practice, depending on context.', 'The four-stage model of life is one framework among many and has been interpreted differently across history. Ashrama can also simply mean a place where a teacher or community practices.', 'A stage of life, a hermitage, or a community of spiritual practice, depending on context.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000741', 'varna', 'Varna', 'वर्ण', 'A historical classification discussed in some Hindu texts and social theories.', 'Varna is not interchangeable with every form of caste or with a person’s worth. Caste-based discrimination has caused and continues to cause real harm; Dharma Daily does not endorse hierarchy or exclusion.', 'A historical classification discussed in some Hindu texts and social theories.', '{}'::text[], '{"note":"Texts, historians, communities, and contemporary thinkers debate how varna relates to jati, occupation, conduct, and later social systems."}'::jsonb),
  ('00000000-0000-0000-0000-000000000742', 'guru', 'Guru', 'गुरु', 'A teacher or guide, especially in a spiritual or educational lineage.', 'A guru may have a formal lineage role, while the word is also used broadly for a skilled teacher. Healthy discernment, consent, boundaries, and accountability matter in every teacher-student relationship.', 'A teacher or guide, especially in a spiritual or educational lineage.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000743', 'shakti', 'Shakti', 'शक्ति', 'Power, energy, or the divine feminine principle in many Hindu traditions.', 'Shakti may be understood as a goddess, cosmic power, the active aspect of the divine, or a name within a particular theology. Shakta traditions are diverse and should not be flattened into one view.', 'Power, energy, or the divine feminine principle in many Hindu traditions.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000744', 'lila', 'Lila', 'लीला', 'Divine play or the unfolding of reality as a meaningful expression.', 'Lila appears in devotional and philosophical language, especially in accounts of divine forms and stories. It should not be used to dismiss someone’s pain or excuse harmful behaviour.', 'Divine play or the unfolding of reality as a meaningful expression.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000745', 'ishta-devata', 'Ishta Devata', 'इष्टदेवता', 'A chosen or personally cherished form of the divine.', 'A person’s ishta devata may come through family practice, initiation, devotion, or personal relationship. Traditions differ on how this choice is understood and guided.', 'A chosen or personally cherished form of the divine.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000746', 'shraddha', 'Shraddha', 'श्रद्धा', 'Trust, faith, confidence, or a sincere orientation toward practice and understanding.', 'Shraddha is not blind certainty in every usage. It can mean the trust that makes study and practice possible while remaining open to discernment and experience.', 'Trust, faith, confidence, or a sincere orientation toward practice and understanding.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000747', 'vairagya', 'Vairagya', 'वैराग्य', 'Freedom from compulsive attachment and possessiveness.', 'Vairagya is often paired with practice and discernment. It is not emotional numbness, contempt for the world, or permission to abandon responsibilities.', 'Freedom from compulsive attachment and possessiveness.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000748', 'viveka', 'Viveka', 'विवेक', 'Discernment: the ability to distinguish what is helpful, lasting, true, or appropriate.', 'Viveka is cultivated through reflection, study, experience, and guidance. It can help hold devotion and critical thinking together rather than setting them against each other.', 'Discernment: the ability to distinguish what is helpful, lasting, true, or appropriate.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000749', 'upasana', 'Upasana', 'उपासना', 'A practice of drawing near to the divine through worship, meditation, or contemplation.', 'Upasana can include visualisation, mantra, ritual, and loving attention. The form and purpose depend on the tradition, deity, and teacher involved.', 'A practice of drawing near to the divine through worship, meditation, or contemplation.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb),
  ('00000000-0000-0000-0000-000000000750', 'namaste', 'Namaste', 'नमस्ते', 'A respectful greeting or gesture whose meaning is shaped by language and context.', 'Namaste is widely used in South Asian and global settings, but it is not a single mandatory religious ritual. Pronunciation, gesture, and social meaning vary by region and community.', 'A respectful greeting or gesture whose meaning is shaped by language and context.', '{}'::text[], '{"note":"Emphasis and meaning vary across texts, philosophical schools, families, and teachers."}'::jsonb)
on conflict (slug) do update set
  term = excluded.term,
  term_sanskrit = excluded.term_sanskrit,
  short_definition = excluded.short_definition,
  full_explanation = excluded.full_explanation,
  examples = excluded.examples,
  related_concepts = excluded.related_concepts,
  tradition_variations = excluded.tradition_variations;

-- ---------------------------------------------------------------------------
-- practice_guides (20)
-- ---------------------------------------------------------------------------
insert into public.practice_guides (id, slug, title, category, difficulty, duration_minutes, steps, materials_needed, tradition_notes, warnings, is_premium) values
  ('00000000-0000-0000-0000-000000000503', 'three-breath-return', 'Three-breath return', 'meditation', 'beginner', 2, '[{"order":1,"title":"Step 1","body":"Sit in a comfortable, steady position."},{"order":2,"title":"Step 2","body":"Let your breathing stay natural."},{"order":3,"title":"Step 3","body":"Notice each inhale and exhale without forcing it."},{"order":4,"title":"Step 4","body":"When the mind wanders, return gently to the breath."},{"order":5,"title":"Step 5","body":"End by naming one quality you want to carry forward."}]'::jsonb, '{}'::text[], 'A small pause to notice the breath and return to the present moment.', null, false),
  ('00000000-0000-0000-0000-000000000501', 'morning-diya-lighting', 'Morning Diya Lighting', 'puja', 'beginner', 5, '[{"order":1,"title":"Step 1","body":"Place the diya on a stable, heat-safe surface."},{"order":2,"title":"Step 2","body":"Take a quiet moment to settle."},{"order":3,"title":"Step 3","body":"Light the wick safely."},{"order":4,"title":"Step 4","body":"Offer a short prayer, mantra, or silent intention."},{"order":5,"title":"Step 5","body":"Remain for a few breaths, then extinguish safely if it cannot be supervised."}]'::jsonb, ARRAY['Diya or oil lamp', 'Wick', 'Oil or ghee', 'Matches or lighter', 'Heat-safe plate']::text[], 'A simple home practice using light as a reminder of clarity and presence.

Tradition note: Customs around direction, timing, oil, and accompanying prayers vary. Follow your family or teacher’s practice where relevant.', 'Never leave a flame unattended. Keep diyas away from children, pets, curtains, and other flammable materials, and extinguish them fully before leaving.', false),
  ('00000000-0000-0000-0000-000000000504', 'evening-gratitude-reflection', 'Evening gratitude reflection', 'meditation', 'beginner', 4, '[{"order":1,"title":"Step 1","body":"Recall one moment of support."},{"order":2,"title":"Step 2","body":"Name one action you are grateful you took."},{"order":3,"title":"Step 3","body":"Notice one place where you can make amends or try again."},{"order":4,"title":"Step 4","body":"Write a single intention for tomorrow."}]'::jsonb, '{}'::text[], 'Close the day by noticing what supported you and where you can respond with care.', null, false),
  ('00000000-0000-0000-0000-000000000505', 'a-simple-repetition-practice', 'A simple repetition practice', 'mantra', 'beginner', 5, '[{"order":1,"title":"Step 1","body":"Sit comfortably and let your breathing remain natural."},{"order":2,"title":"Step 2","body":"If you have a mantra or sacred name from your family or teacher, use that; otherwise choose a short word or phrase meaningful to you."},{"order":3,"title":"Step 3","body":"Repeat it gently, aloud or silently, at a pace that feels steady."},{"order":4,"title":"Step 4","body":"When attention wanders, return without scolding yourself."},{"order":5,"title":"Step 5","body":"Close with one quiet breath and carry the quality of the practice into your next action."}]'::jsonb, '{}'::text[], 'A quiet repetition practice grounded in your own family, teacher, or intention.

Tradition note: Mantra, japa, names of the divine, initiation, pronunciation, and counting customs differ across traditions. This is a general introduction, not lineage-specific instruction.', null, false),
  ('00000000-0000-0000-0000-000000000502', 'an-evening-practice-of-return', 'An evening practice of return', 'meditation', 'intermediate', 10, '[{"order":1,"title":"Step 1","body":"Let the day settle before reviewing it."},{"order":2,"title":"Step 2","body":"Name one action that reflected care."},{"order":3,"title":"Step 3","body":"Name one moment you would handle differently."},{"order":4,"title":"Step 4","body":"Choose a repair or a small experiment for tomorrow."},{"order":5,"title":"Step 5","body":"Close with three natural breaths and let the review end."}]'::jsonb, '{}'::text[], 'Review the day without turning mistakes into a permanent identity.

Tradition note: This is an app-authored reflective exercise. Families, teachers, and traditions may use different evening practices.', null, true),
  ('00000000-0000-0000-0000-000000000506', 'a-five-minute-breath-pause', 'A five-minute breath pause', 'meditation', 'beginner', 5, '[{"order":1,"title":"Step 1","body":"Sit or stand in a comfortable position."},{"order":2,"title":"Step 2","body":"Let the breath remain natural; do not force its depth or pace."},{"order":3,"title":"Step 3","body":"Notice the beginning, middle, and end of one breath."},{"order":4,"title":"Step 4","body":"When attention wanders, name it softly and return."},{"order":5,"title":"Step 5","body":"End by noticing one thing you want to do with care."}]'::jsonb, '{}'::text[], 'A gentle attention practice with natural breathing and no breath retention.

Tradition note: This is an app-authored attention exercise, not medical or lineage-specific breath instruction.', null, false),
  ('00000000-0000-0000-0000-000000000507', 'a-body-aware-sitting-pause', 'A body-aware sitting pause', 'meditation', 'beginner', 7, '[{"order":1,"title":"Step 1","body":"Choose a supported seat and let your hands rest."},{"order":2,"title":"Step 2","body":"Notice contact with the floor or chair."},{"order":3,"title":"Step 3","body":"Move attention slowly from face to shoulders, hands, torso, and feet."},{"order":4,"title":"Step 4","body":"Meet areas of tension with curiosity rather than force."},{"order":5,"title":"Step 5","body":"Return to the whole body and finish gently."}]'::jsonb, '{}'::text[], 'Notice the body as it is, without turning sensation into a verdict.

Tradition note: Stop if a body-focused exercise feels distressing and choose an outward-looking practice instead.', null, false),
  ('00000000-0000-0000-0000-000000000508', 'morning-intention', 'Morning intention', 'meditation', 'beginner', 4, '[{"order":1,"title":"Step 1","body":"Name the first responsibility in front of you."},{"order":2,"title":"Step 2","body":"Choose one quality such as patience, honesty, or steadiness."},{"order":3,"title":"Step 3","body":"Imagine one ordinary moment in which you can practise it."},{"order":4,"title":"Step 4","body":"Write a short sentence beginning with ‘Today I will…’."},{"order":5,"title":"Step 5","body":"Take one natural breath and begin."}]'::jsonb, '{}'::text[], 'Choose one quality to bring into the next part of the day.', null, false),
  ('00000000-0000-0000-0000-000000000509', 'a-gratitude-walk', 'A gratitude walk', 'meditation', 'beginner', 10, '[{"order":1,"title":"Step 1","body":"Choose a safe route or walk slowly in one room."},{"order":2,"title":"Step 2","body":"Notice three ordinary things supporting your life today."},{"order":3,"title":"Step 3","body":"Offer silent thanks without needing to name a deity or belief."},{"order":4,"title":"Step 4","body":"Notice one way you might offer support in return."},{"order":5,"title":"Step 5","body":"Return to your day with one small act of care."}]'::jsonb, '{}'::text[], 'Let movement and attention make room for gratitude without forcing cheerfulness.', null, false),
  ('00000000-0000-0000-0000-000000000510', 'a-mindful-meal', 'A mindful meal', 'meditation', 'beginner', 10, '[{"order":1,"title":"Step 1","body":"Pause before eating and notice the food in front of you."},{"order":2,"title":"Step 2","body":"Remember one person, creature, or process that helped bring it here."},{"order":3,"title":"Step 3","body":"Take the first few bites without a screen."},{"order":4,"title":"Step 4","body":"Notice taste, texture, and the body’s signals."},{"order":5,"title":"Step 5","body":"Finish with gratitude or a quiet intention to waste less."}]'::jsonb, '{}'::text[], 'Receive one meal with attention to effort, nourishment, and shared life.', null, false),
  ('00000000-0000-0000-0000-000000000511', 'a-compassionate-response', 'A compassionate response', 'meditation', 'beginner', 5, '[{"order":1,"title":"Step 1","body":"Recall a moment that felt difficult without replaying every detail."},{"order":2,"title":"Step 2","body":"Name the feeling in plain language."},{"order":3,"title":"Step 3","body":"Ask what a kind but honest response would look like."},{"order":4,"title":"Step 4","body":"Choose one boundary, repair, or supportive action."},{"order":5,"title":"Step 5","body":"Let the practice end without demanding instant forgiveness."}]'::jsonb, '{}'::text[], 'Practise meeting a difficult moment with care for yourself and others.

Tradition note: This is reflective education, not therapy or crisis support.', null, false),
  ('00000000-0000-0000-0000-000000000512', 'study-before-opinion', 'Study before opinion', 'meditation', 'beginner', 8, '[{"order":1,"title":"Step 1","body":"Choose one paragraph from a reviewed source or app concept."},{"order":2,"title":"Step 2","body":"Read it once for the main claim."},{"order":3,"title":"Step 3","body":"Read it again and mark one word you do not understand."},{"order":4,"title":"Step 4","body":"Write one question rather than rushing to a conclusion."},{"order":5,"title":"Step 5","body":"Keep the question open for further study or qualified guidance."}]'::jsonb, '{}'::text[], 'Create a small habit of asking what a teaching actually says before reacting to it.', null, false),
  ('00000000-0000-0000-0000-000000000513', 'evening-release', 'Evening release', 'meditation', 'beginner', 7, '[{"order":1,"title":"Step 1","body":"Let the day settle before reviewing it."},{"order":2,"title":"Step 2","body":"Name one action that reflected care."},{"order":3,"title":"Step 3","body":"Name one moment you would handle differently."},{"order":4,"title":"Step 4","body":"Choose a repair or a small experiment for tomorrow."},{"order":5,"title":"Step 5","body":"Close with three natural breaths and let the review end."}]'::jsonb, '{}'::text[], 'Review the day without turning mistakes into a permanent identity.', null, false),
  ('00000000-0000-0000-0000-000000000514', 'offer-a-cup-of-water', 'Offer a cup of water', 'puja', 'beginner', 5, '[{"order":1,"title":"Step 1","body":"Place a clean cup or small bowl on a stable surface."},{"order":2,"title":"Step 2","body":"Pause and name what you are grateful for."},{"order":3,"title":"Step 3","body":"Offer the water according to your family or teacher’s custom, if you have one."},{"order":4,"title":"Step 4","body":"Sit for a few breaths without asking for a particular result."},{"order":5,"title":"Step 5","body":"Return the water respectfully and clean the space."}]'::jsonb, ARRAY['Clean cup or small bowl', 'Water']::text[], 'A simple app-authored offering practice for people who already want a quiet home ritual.

Tradition note: Offerings and procedures differ by deity, household, region, and lineage.', null, false),
  ('00000000-0000-0000-0000-000000000515', 'refresh-a-small-sacred-space', 'Refresh a small sacred space', 'puja', 'beginner', 10, '[{"order":1,"title":"Step 1","body":"Choose a small area that can be cleaned safely."},{"order":2,"title":"Step 2","body":"Remove clutter and wipe the surface."},{"order":3,"title":"Step 3","body":"Place only items that belong to your own practice or intention."},{"order":4,"title":"Step 4","body":"Offer a short prayer, greeting, or moment of silence."},{"order":5,"title":"Step 5","body":"Leave the area ready for the next person who uses it."}]'::jsonb, ARRAY['Clean cloth']::text[], 'Care for a prayer, study, or reflection space without prescribing one correct altar.

Tradition note: Some households keep a murti, image, lamp, book, or no object at all; follow your own context.', null, false),
  ('00000000-0000-0000-0000-000000000516', 'a-simple-arati-preparation', 'A simple arati preparation', 'puja', 'beginner', 8, '[{"order":1,"title":"Step 1","body":"Choose a stable, heat-safe surface away from anything flammable."},{"order":2,"title":"Step 2","body":"Prepare a diya only if supervised and appropriate for your home."},{"order":3,"title":"Step 3","body":"Pause before lighting and remember the purpose of the gesture."},{"order":4,"title":"Step 4","body":"Follow your family or temple’s practice for prayer or movement."},{"order":5,"title":"Step 5","body":"Extinguish the flame fully and leave the area safe."}]'::jsonb, ARRAY['Diya or lamp', 'Wick', 'Oil or ghee', 'Heat-safe plate']::text[], 'Prepare a safe moment of light and gratitude without presenting a full ritual procedure.

Tradition note: Arati forms, words, timing, and movement differ widely; this is only a safety-conscious preparation guide.', 'Never leave a flame unattended. Keep fire away from children, pets, curtains, and other flammable materials.', true),
  ('00000000-0000-0000-0000-000000000517', 'japa-with-a-chosen-phrase', 'Japa with a chosen phrase', 'mantra', 'beginner', 8, '[{"order":1,"title":"Step 1","body":"Sit comfortably and let breathing remain natural."},{"order":2,"title":"Step 2","body":"Choose a phrase already appropriate for your family or teacher, if you have one."},{"order":3,"title":"Step 3","body":"Otherwise choose a short non-harmful word or phrase for this introductory exercise."},{"order":4,"title":"Step 4","body":"Repeat at a steady, unforced pace."},{"order":5,"title":"Step 5","body":"Stop after a few minutes and carry the quality of attention into one action."}]'::jsonb, '{}'::text[], 'A gentle repetition practice that leaves the mantra choice with the user’s tradition or teacher.

Tradition note: Initiation, pronunciation, eligibility, counting, and mantra choice are lineage-specific; this guide does not replace instruction.', null, true),
  ('00000000-0000-0000-0000-000000000518', 'mala-preparation', 'Mala preparation', 'mantra', 'beginner', 5, '[{"order":1,"title":"Step 1","body":"Place the mala on a clean surface or hold it comfortably."},{"order":2,"title":"Step 2","body":"Notice its material and any family or lineage significance."},{"order":3,"title":"Step 3","body":"Ask what counting and handling customs apply in your tradition."},{"order":4,"title":"Step 4","body":"If you have no instruction, use it only as a quiet attention object."},{"order":5,"title":"Step 5","body":"Store it respectfully when you finish."}]'::jsonb, ARRAY['Mala or prayer beads']::text[], 'Learn how to approach prayer beads respectfully without prescribing a counting method.

Tradition note: Bead counts, hand position, mantras, and handling customs differ; seek qualified instruction for formal practice.', null, true),
  ('00000000-0000-0000-0000-000000000519', 'a-seva-intention', 'A seva intention', 'meditation', 'beginner', 12, '[{"order":1,"title":"Step 1","body":"Notice one need in your household or community."},{"order":2,"title":"Step 2","body":"Ask what help is actually wanted rather than assuming."},{"order":3,"title":"Step 3","body":"Choose a small action that fits your time and ability."},{"order":4,"title":"Step 4","body":"Do it without using the recipient’s gratitude as a measure of success."},{"order":5,"title":"Step 5","body":"Reflect on what you learned about service and dignity."}]'::jsonb, '{}'::text[], 'Turn appreciation into one concrete act of service that respects consent and capacity.', null, false),
  ('00000000-0000-0000-0000-000000000520', 'weekly-teaching-review', 'Weekly teaching review', 'meditation', 'intermediate', 15, '[{"order":1,"title":"Step 1","body":"Choose one reviewed concept, passage, or tradition note."},{"order":2,"title":"Step 2","body":"Write the teaching’s central question in your own words."},{"order":3,"title":"Step 3","body":"Name one place where it agrees with your experience and one where it challenges you."},{"order":4,"title":"Step 4","body":"Record a question for a teacher, elder, or further reading."},{"order":5,"title":"Step 5","body":"Choose one modest experiment for the week ahead."}]'::jsonb, '{}'::text[], 'Return to one teaching and connect it to a real decision without forcing a perfect answer.', null, true)
on conflict (slug) do update set
  title = excluded.title,
  category = excluded.category,
  difficulty = excluded.difficulty,
  duration_minutes = excluded.duration_minutes,
  steps = excluded.steps,
  materials_needed = excluded.materials_needed,
  tradition_notes = excluded.tradition_notes,
  warnings = excluded.warnings,
  is_premium = excluded.is_premium;

-- ---------------------------------------------------------------------------
-- daily_reflections (30)
-- ---------------------------------------------------------------------------
insert into public.daily_reflections (id, date_slot, title, shloka_passage_id, reflection_text, practice_prompt, journal_prompt, tradition, tags, is_premium) values
  ('00000000-0000-0000-0000-000000000301', 1, 'Give yourself fully to the action, then soften your grip on the outcome.', null, 'Today, choose one responsibility that matters. Meet it with care and attention—not because you can control every result, but because the quality of your action is yours to shape.', 'Choose one responsibility. Before you begin, take a breath and name the care you want to bring to it.', 'What is one action I can do with care today, without demanding a particular result?', 'general', ARRAY['app-authored']::text[], false),
  ('00000000-0000-0000-0000-000000000302', 2, 'Let attention become care', null, 'Attention is not only a way to get more done. It can be a way of telling a person, task, or moment that it matters. Begin with one thing and give it your unhurried presence.', 'Choose one ordinary task and do the first two minutes without switching away.', 'What changed when I gave one thing my full attention?', 'general', ARRAY['app-authored']::text[], false),
  ('00000000-0000-0000-0000-000000000303', 3, 'The next honest step', null, 'A whole life can feel too large to repair at once. Dharma is often approached through the next honest step: one conversation, one responsibility, one act that reduces harm.', 'Name one next step and make it small enough to begin today.', 'Which next step is mine to take, and what support would make it possible?', 'general', ARRAY['app-authored']::text[], false),
  ('00000000-0000-0000-0000-000000000304', 4, 'Receive before reaching', null, 'The mind often rushes toward the next want before noticing what has already arrived. Receiving is not complacency; it is the pause that lets gratitude and discernment enter the day.', 'Before your next meal or drink, pause for one breath and notice what is being offered.', 'What support did I receive today that I usually overlook?', 'general', ARRAY['app-authored']::text[], false),
  ('00000000-0000-0000-0000-000000000305', 5, 'A boundary can be dharmic', null, 'Care does not always look like availability. A clear boundary can protect dignity, prevent resentment, and make a more truthful relationship possible.', 'Write one kind sentence that names a limit you need to keep.', 'Where would a clear boundary reduce harm rather than create distance?', 'general', ARRAY['app-authored']::text[], false),
  ('00000000-0000-0000-0000-000000000306', 6, 'Begin again without drama', null, 'Returning is part of practice. The mind wanders, plans fail, and attention gets lost; beginning again is not evidence that the earlier effort was wasted.', 'When you notice you have drifted, say ‘return’ and take one uncomplicated next action.', 'What helps me begin again without criticising myself?', 'general', ARRAY['app-authored']::text[], false),
  ('00000000-0000-0000-0000-000000000307', 7, 'Make room for another view', null, 'Traditions stay alive through conversation, interpretation, and lived experience. Making room for another view does not require abandoning discernment or pretending every claim is equal.', 'Ask someone a sincere question about how they understand a practice before explaining your own view.', 'What did I learn when I listened without preparing a rebuttal?', 'general', ARRAY['app-authored']::text[], false),
  ('00000000-0000-0000-0000-000000000308', 8, 'The quality of the offering', null, 'An offering is shaped not only by what is placed before the divine, but by the attention and relationship carried into the act. A small offering can be sincere; a grand one can be hurried.', 'Do one small act of giving with care and without announcing it.', 'What quality do I want my offerings of time, food, or attention to carry?', 'general', ARRAY['app-authored']::text[], false),
  ('00000000-0000-0000-0000-000000000309', 9, 'Do not turn a feeling into a prophecy', null, 'A heavy mood can tell you something needs attention, but it does not always tell you what will happen next. Notice the feeling, seek support when needed, and leave room for the day to change.', 'Name one feeling and one fact without treating either as the whole story.', 'What becomes possible when I allow a feeling to be real but temporary?', 'general', ARRAY['app-authored']::text[], false),
  ('00000000-0000-0000-0000-000000000310', 10, 'Learning has a pace', null, 'A sacred text, philosophical idea, or ritual cannot be fully understood in a single sitting. Slow study is not failure; it is a way of respecting complexity.', 'Choose one unfamiliar word and look at it again rather than rushing through the page.', 'What would it mean to let this teaching take the time it needs?', 'general', ARRAY['app-authored']::text[], false),
  ('00000000-0000-0000-0000-000000000311', 11, 'Care for the conditions', null, 'Practice depends on conditions: sleep, food, time, safety, and people who help us. Spiritual aspiration does not require pretending those conditions are irrelevant.', 'Improve one small condition that would make today’s practice more possible.', 'What practical support would help my values become more consistent?', 'general', ARRAY['app-authored']::text[], false),
  ('00000000-0000-0000-0000-000000000312', 12, 'A name can be a doorway', null, 'Names of the divine carry family memory, poetry, theology, and affection. The same name may be approached differently across communities; curiosity is a respectful beginning.', 'Write one name or quality of the divine that matters to you, and one question about it.', 'What relationship or story does this name open for me?', 'general', ARRAY['app-authored']::text[], false),
  ('00000000-0000-0000-0000-000000000313', 13, 'Repair is an action', null, 'Regret can remain a private feeling, or it can become a repair. A repair may be an apology, a changed habit, a returned resource, or an honest conversation with no guarantee of immediate relief.', 'Choose one repair that is safe, specific, and within your responsibility.', 'What would repair look like beyond saying that I am sorry?', 'general', ARRAY['app-authored']::text[], false),
  ('00000000-0000-0000-0000-000000000314', 14, 'The sacred in the ordinary', null, 'Daily life is where ideals meet limits. Washing, working, caring, studying, and resting can all become places to practise attention without needing to make them dramatic.', 'Choose one routine action and perform it as deliberately as a short ritual.', 'Where did ordinary life already ask me for reverence today?', 'general', ARRAY['app-authored']::text[], false),
  ('00000000-0000-0000-0000-000000000315', 15, 'Let praise pass through', null, 'Praise can be received with gratitude without becoming a new demand to perform. Let kind words encourage you, then return to the work itself.', 'Receive one compliment with a simple ‘thank you’ and no argument or performance.', 'How can I value appreciation without making it the source of my worth?', 'general', ARRAY['app-authored']::text[], false),
  ('00000000-0000-0000-0000-000000000316', 16, 'A question is a practice', null, 'Some questions are not problems to eliminate. They can keep study humble, protect us from certainty, and lead us toward better guidance.', 'Write one honest question and resist answering it immediately.', 'Which question would make my learning more careful?', 'general', ARRAY['app-authored']::text[], false),
  ('00000000-0000-0000-0000-000000000317', 17, 'Gratitude without comparison', null, 'Gratitude does not require pretending that someone else has less to be thankful for or that your own difficulty is invalid. It can be specific, grounded, and free of comparison.', 'Name one thing that helped you without using another person’s hardship as a contrast.', 'What kind of gratitude feels honest in my actual circumstances?', 'general', ARRAY['app-authored']::text[], false),
  ('00000000-0000-0000-0000-000000000318', 18, 'The pause before speech', null, 'Words can create a world around them. A brief pause can help truth, kindness, and responsibility arrive together before a sentence leaves the mouth.', 'Before one difficult reply, take one breath and ask what outcome you are serving.', 'What did my words make easier or harder today?', 'general', ARRAY['app-authored']::text[], false),
  ('00000000-0000-0000-0000-000000000319', 19, 'Devotion can include questions', null, 'Love for a deity, teacher, text, or tradition is not always quiet agreement. Devotion can also bring honest questions, grief, and the courage to seek a deeper understanding.', 'Write one question you can bring respectfully to your tradition or a trusted teacher.', 'Which question has my devotion been making room for?', 'general', ARRAY['app-authored']::text[], false),
  ('00000000-0000-0000-0000-000000000320', 20, 'Do the work in front of you', null, 'A meaningful life is built through many unglamorous actions. The work in front of you may be small, but it can still be done with dignity and care.', 'Give ten undivided minutes to one responsibility you have been postponing.', 'What changes when I stop waiting for the perfect task?', 'general', ARRAY['app-authored']::text[], false),
  ('00000000-0000-0000-0000-000000000321', 21, 'Rest is not a moral failure', null, 'A practice that makes a person despise their limits has lost some of its care. Rest can protect the body and make sustained service possible.', 'Take a short, guilt-free pause and notice what it restores.', 'What would responsible rest look like today?', 'general', ARRAY['app-authored']::text[], false),
  ('00000000-0000-0000-0000-000000000322', 22, 'Notice the story you add', null, 'Events happen, and then the mind often adds a story about what they prove. Discernment can separate the event, the feeling, the interpretation, and the next choice.', 'Write four short lines: what happened, what I felt, what I assumed, what I can choose.', 'Which part of today was an event, and which part was my story about it?', 'general', ARRAY['app-authored']::text[], false),
  ('00000000-0000-0000-0000-000000000323', 23, 'Keep the door open', null, 'A tradition can be a home and a field of learning. You can honour what shaped you while continuing to learn from people, texts, and communities beyond your first experience.', 'Read one short, respectful introduction to a Hindu tradition different from your own.', 'What can I learn without treating another tradition as a curiosity or a threat?', 'general', ARRAY['app-authored']::text[], false),
  ('00000000-0000-0000-0000-000000000324', 24, 'Give attention a place', null, 'The mind follows the conditions around it. A small dedicated place or time can make practice easier, not because the place is magical, but because repetition teaches the body what to expect.', 'Choose one repeatable time and place for two minutes of reflection this week.', 'Which condition would make returning to practice more natural?', 'general', ARRAY['app-authored']::text[], false),
  ('00000000-0000-0000-0000-000000000325', 25, 'A lamp needs tending', null, 'The image of a lamp is useful because light is not only lit once. Attention, relationship, and ethical courage also need tending through ordinary choices.', 'Identify one quality you want to tend and one action that gives it fuel.', 'What needs tending rather than demanding?', 'general', ARRAY['app-authored']::text[], false),
  ('00000000-0000-0000-0000-000000000326', 26, 'Choose less, notice more', null, 'A crowded day can make every object and message feel urgent. Choosing less for a short while can reveal what was asking for attention all along.', 'Put one nonessential item or notification aside for an hour.', 'What did I notice when I reduced one source of noise?', 'general', ARRAY['app-authored']::text[], false),
  ('00000000-0000-0000-0000-000000000327', 27, 'Respect the threshold', null, 'Beginnings and endings deserve a little attention. A greeting, closing gesture, or moment of thanks can help the mind recognise a change in relationship.', 'Mark the beginning or end of one activity with a breath and a clear intention.', 'Which transition in my day could use more care?', 'general', ARRAY['app-authored']::text[], false),
  ('00000000-0000-0000-0000-000000000328', 28, 'Do not borrow certainty', null, 'A confident voice can make an interpretation sound universal. Wisdom includes asking whose view is being offered, what its sources are, and where other traditions differ.', 'When you hear a spiritual claim, ask what kind of authority it represents.', 'Where did I mistake confidence for truth today?', 'general', ARRAY['app-authored']::text[], false),
  ('00000000-0000-0000-0000-000000000329', 29, 'Make kindness concrete', null, 'Kindness becomes trustworthy when it takes a form another person can actually receive. It may be time, clarity, practical help, or the restraint to stop causing harm.', 'Ask one person what support would be useful before offering your preferred solution.', 'How did I make care tangible today?', 'general', ARRAY['app-authored']::text[], false),
  ('00000000-0000-0000-0000-000000000330', 30, 'Carry one thing forward', null, 'A reflection does not need to change everything. Let one sentence, question, or quality travel with you into the next ordinary action.', 'Choose one phrase from today and repeat it before your next responsibility.', 'What is worth carrying forward, and what can I leave here?', 'general', ARRAY['app-authored']::text[], false)
on conflict (date_slot, tradition) do update set
  id = excluded.id,
  title = excluded.title,
  shloka_passage_id = excluded.shloka_passage_id,
  reflection_text = excluded.reflection_text,
  practice_prompt = excluded.practice_prompt,
  journal_prompt = excluded.journal_prompt,
  tags = excluded.tags,
  is_premium = excluded.is_premium;

-- ---------------------------------------------------------------------------
-- festival explainers (21)
-- ---------------------------------------------------------------------------
insert into public.festivals (id, slug, name, name_variants, short_description, full_story, meaning, home_observance, regional_variations, traditions, tithi_rule, upcoming_dates, duration_days, is_premium) values
  ('00000000-0000-0000-0000-000000000402', 'guru-purnima', 'Guru Purnima', '{}'::text[], 'A day of gratitude for teachers and the lineages of learning.', 'Guru Purnima honours teachers—spiritual and otherwise—who help remove confusion and illuminate understanding.', 'Guru Purnima honours teachers—spiritual and otherwise—who help remove confusion and illuminate understanding.', 'Offer gratitude to a teacher or mentor
Read or revisit a teaching that shaped you
Make a quiet act of service', '{"note":"Observances differ by lineage, region, and family. Buddhist and Jain communities also mark this full moon in distinct ways."}'::jsonb, ARRAY['general']::text[], 'Authored date; local observance timing varies by region and tradition.', ARRAY['2026-07-29'::date], 1, false),
  ('00000000-0000-0000-0000-000000000403', 'raksha-bandhan', 'Raksha Bandhan', '{}'::text[], 'A celebration of care, protection, and sibling bonds.', 'Raksha Bandhan centres on a bond of mutual care, often symbolised by tying a rakhi.', 'Raksha Bandhan centres on a bond of mutual care, often symbolised by tying a rakhi.', 'Share a rakhi or message of care
Offer sweets
Reflect on mutual responsibility', '{"note":"The relationship celebrated and the ritual details vary widely across communities."}'::jsonb, ARRAY['general']::text[], 'Authored date; local observance timing varies by region and tradition.', ARRAY['2026-08-28'::date], 1, false),
  ('00000000-0000-0000-0000-000000000404', 'krishna-janmashtami', 'Krishna Janmashtami', ARRAY['Gokulashtami']::text[], 'Celebrating the birth of Krishna through devotion, song, and story.', 'Janmashtami remembers Krishna’s birth and the divine presence expressed through love, play, courage, and dharma.', 'Janmashtami remembers Krishna’s birth and the divine presence expressed through love, play, courage, and dharma.', 'Read a Krishna story
Sing or listen to bhajans
Prepare a simple offering if this is part of your tradition', '{"note":"Fasting, midnight worship, temple customs, and calendar dates vary by region and sampradaya."}'::jsonb, ARRAY['general']::text[], 'Authored date; local observance timing varies by region and tradition.', ARRAY['2026-09-04'::date], 1, false),
  ('00000000-0000-0000-0000-000000000401', 'diwali', 'Diwali', ARRAY['Deepavali']::text[], 'A festival of light observed through stories, worship, generosity, and renewal.', 'Diwali is understood differently across communities, including celebrations connected with Rama, Lakshmi, Krishna, or Kali.', 'Diwali is understood differently across communities, including celebrations connected with Rama, Lakshmi, Krishna, or Kali.', 'Light a diya safely if this is part of your practice
Offer gratitude or a prayer in your own tradition
Share food, generosity, or a kind act', '{"note":"Names, dates, stories, fasting, and observances vary by region, calendar method, and tradition."}'::jsonb, ARRAY['general']::text[], 'Authored date; local observance timing varies by region and tradition.', ARRAY['2026-11-08'::date], 1, false),
  ('00000000-0000-0000-0000-000000000405', 'maha-shivaratri', 'Maha Shivaratri', ARRAY['Shivratri']::text[], 'A night of devotion, remembrance, and attention associated with Shiva.', 'Maha Shivaratri is observed through prayer, vigil, fasting, mantra, and stories in different Shaiva and wider Hindu communities.', 'Maha Shivaratri is observed through prayer, vigil, fasting, mantra, and stories in different Shaiva and wider Hindu communities.', 'Learn which observance your family or temple follows
Offer a quiet prayer or act of service
Avoid fasting unless it is safe and appropriate for you', '{"note":"Fasting, night vigils, dates, and forms of worship vary by region, sampradaya, health, and family custom."}'::jsonb, ARRAY['general']::text[], 'Calendar dates require reviewed calendar data; this row is an explainer.', '{}'::date[], 1, false),
  ('00000000-0000-0000-0000-000000000406', 'holi', 'Holi', '{}'::text[], 'A spring festival associated with colour, community, stories, and renewal.', 'Holi includes several regional histories and observances, including Holika Dahan and celebrations of Krishna in some communities.', 'Holi includes several regional histories and observances, including Holika Dahan and celebrations of Krishna in some communities.', 'Join only celebrations where consent and safety are respected
Offer a greeting or colour-free act of welcome
Learn the local story before assuming one meaning', '{"note":"Names, stories, timing, colours, food, and public customs differ widely across regions and communities."}'::jsonb, ARRAY['general']::text[], 'Calendar dates require reviewed calendar data; this row is an explainer.', '{}'::date[], 1, false),
  ('00000000-0000-0000-0000-000000000407', 'navaratri', 'Navaratri', '{}'::text[], 'Nine nights of devotion and reflection connected with forms of the divine feminine.', 'Navaratri may honour Durga, Lakshmi, Saraswati, or other forms and can include dance, music, fasting, worship, and community gatherings.', 'Navaratri may honour Durga, Lakshmi, Saraswati, or other forms and can include dance, music, fasting, worship, and community gatherings.', 'Choose a form of observance that belongs to your tradition
Make space for learning, music, or service
Treat fasting as optional and seek medical advice when relevant', '{"note":"The nine nights, deities, stories, foods, dances, and dates vary by region and lineage."}'::jsonb, ARRAY['general']::text[], 'Calendar dates require reviewed calendar data; this row is an explainer.', '{}'::date[], 1, true),
  ('00000000-0000-0000-0000-000000000408', 'durga-puja', 'Durga Puja', '{}'::text[], 'A major celebration of Durga through image worship, story, art, music, and community.', 'Durga Puja is especially associated with Bengal and eastern India, while related celebrations appear in many places with distinct forms and meanings.', 'Durga Puja is especially associated with Bengal and eastern India, while related celebrations appear in many places with distinct forms and meanings.', 'Visit or learn from a community celebration respectfully
Read a regional account of the festival
Offer service or generosity alongside celebration', '{"note":"Iconography, days, rituals, food, language, and community roles vary by region and temple tradition."}'::jsonb, ARRAY['general']::text[], 'Calendar dates require reviewed calendar data; this row is an explainer.', '{}'::date[], 1, true),
  ('00000000-0000-0000-0000-000000000409', 'vijayadashami', 'Vijayadashami', ARRAY['Dussehra']::text[], 'A day of victory, completion, and the return of learning or responsibility.', 'Vijayadashami is connected with different stories, including Rama’s victory and Durga’s triumph, and is also a time for beginning study or honouring tools in some regions.', 'Vijayadashami is connected with different stories, including Rama’s victory and Durga’s triumph, and is also a time for beginning study or honouring tools in some regions.', 'Ask which story your family or community centres
Express gratitude for a skill or teacher
Begin one responsible project with care', '{"note":"The name, story, date, and observances differ across regions and traditions."}'::jsonb, ARRAY['general']::text[], 'Calendar dates require reviewed calendar data; this row is an explainer.', '{}'::date[], 1, false),
  ('00000000-0000-0000-0000-000000000410', 'ganesha-chaturthi', 'Ganesha Chaturthi', '{}'::text[], 'A celebration of Ganesha through welcome, prayer, creativity, and community.', 'Ganesha Chaturthi may include bringing a murti home or to a public celebration, offering food, singing, and a later farewell that reflects local custom.', 'Ganesha Chaturthi may include bringing a murti home or to a public celebration, offering food, singing, and a later farewell that reflects local custom.', 'Learn the environmental and community practices of the celebration near you
Offer a simple act of welcome or learning
Follow local guidance for immersion and materials', '{"note":"Duration, foods, images, processions, immersion, and home observances vary by place and family."}'::jsonb, ARRAY['general']::text[], 'Calendar dates require reviewed calendar data; this row is an explainer.', '{}'::date[], 1, false),
  ('00000000-0000-0000-0000-000000000411', 'vasant-panchami', 'Vasant Panchami', ARRAY['Saraswati Puja']::text[], 'A festival associated with learning, music, spring, and Saraswati in many communities.', 'Vasant Panchami can be a time to honour knowledge, creative work, teachers, and the arrival of spring, with regional forms of worship and celebration.', 'Vasant Panchami can be a time to honour knowledge, creative work, teachers, and the arrival of spring, with regional forms of worship and celebration.', 'Thank a teacher or mentor
Spend a few minutes studying or making music
Place learning before display or performance', '{"note":"The deity focus, colours, offerings, and educational customs differ by region and lineage."}'::jsonb, ARRAY['general']::text[], 'Calendar dates require reviewed calendar data; this row is an explainer.', '{}'::date[], 1, false),
  ('00000000-0000-0000-0000-000000000412', 'makar-sankranti', 'Makar Sankranti', '{}'::text[], 'A solar festival connected with seasonal transition, harvest, and generosity.', 'Makar Sankranti is observed across India under many regional names and customs, including food sharing, bathing, flying kites, and honouring the sun.', 'Makar Sankranti is observed across India under many regional names and customs, including food sharing, bathing, flying kites, and honouring the sun.', 'Learn the regional name used by your family
Share seasonal food safely and generously
Offer gratitude for light, land, and labour', '{"note":"The calendar date is solar but customs, names, foods, and associated observances vary by region."}'::jsonb, ARRAY['general']::text[], 'Calendar dates require reviewed calendar data; this row is an explainer.', '{}'::date[], 1, false),
  ('00000000-0000-0000-0000-000000000413', 'pongal', 'Pongal', ARRAY['Thai Pongal']::text[], 'A Tamil harvest festival of gratitude, abundance, family, and the natural world.', 'Pongal includes several days with distinct practices, including honouring the sun, cattle, household life, and community relationships.', 'Pongal includes several days with distinct practices, including honouring the sun, cattle, household life, and community relationships.', 'Learn the meaning of the day your household observes
Offer thanks to farmers and the natural world
Prepare or share food according to local custom', '{"note":"Days, dishes, decorations, names, and ritual emphasis differ across Tamil communities and locations."}'::jsonb, ARRAY['general']::text[], 'Calendar dates require reviewed calendar data; this row is an explainer.', '{}'::date[], 1, false),
  ('00000000-0000-0000-0000-000000000414', 'onam', 'Onam', '{}'::text[], 'A Kerala festival of welcome, harvest, community, and stories of Mahabali.', 'Onam is celebrated through food, flowers, games, arts, and narratives whose meanings are held differently by communities and families.', 'Onam is celebrated through food, flowers, games, arts, and narratives whose meanings are held differently by communities and families.', 'Learn the story and regional history before simplifying it
Share a meal or act of welcome
Make space for community without excluding others', '{"note":"The story, religious emphasis, food, pookalam, and public celebration differ across Kerala communities and the diaspora."}'::jsonb, ARRAY['general']::text[], 'Calendar dates require reviewed calendar data; this row is an explainer.', '{}'::date[], 1, false),
  ('00000000-0000-0000-0000-000000000415', 'rama-navami', 'Rama Navami', '{}'::text[], 'A celebration connected with Rama, dharma, story, devotion, and moral imagination.', 'Rama Navami may include reading, singing, temple worship, fasting, and retellings of Rama’s life, with different interpretations of the stories and ideals involved.', 'Rama Navami may include reading, singing, temple worship, fasting, and retellings of Rama’s life, with different interpretations of the stories and ideals involved.', 'Read a version of the story with its translator or tradition named
Reflect on one quality the story asks you to examine
Avoid treating one retelling as the only Hindu view', '{"note":"Dates, stories, ritual forms, and theological interpretations differ among regions, texts, and traditions."}'::jsonb, ARRAY['general']::text[], 'Calendar dates require reviewed calendar data; this row is an explainer.', '{}'::date[], 1, false),
  ('00000000-0000-0000-0000-000000000416', 'hanuman-jayanti', 'Hanuman Jayanti', '{}'::text[], 'A celebration of Hanuman through devotion, courage, service, and remembrance.', 'Hanuman is approached in many communities through stories, recitation, temple worship, music, and acts of service.', 'Hanuman is approached in many communities through stories, recitation, temple worship, music, and acts of service.', 'Learn which regional story or form your community follows
Offer help without seeking recognition
Choose recitation only when it belongs to your practice', '{"note":"The date, story, iconography, recitations, and observances vary by region and calendar tradition."}'::jsonb, ARRAY['general']::text[], 'Calendar dates require reviewed calendar data; this row is an explainer.', '{}'::date[], 1, false),
  ('00000000-0000-0000-0000-000000000417', 'akshaya-tritiya', 'Akshaya Tritiya', '{}'::text[], 'A day regarded by many communities as favourable for generosity, learning, or beginning work.', 'Akshaya Tritiya carries different stories and practices across regions. It is often associated with giving, auspicious beginnings, and seasonal or devotional observance.', 'Akshaya Tritiya carries different stories and practices across regions. It is often associated with giving, auspicious beginnings, and seasonal or devotional observance.', 'Choose generosity over unnecessary buying
Begin one modest project with clear intention
Check your family or regional calendar for the day’s customs', '{"note":"The stories, commercial meanings, rituals, and regional importance vary; auspiciousness is not a guarantee of an outcome."}'::jsonb, ARRAY['general']::text[], 'Calendar dates require reviewed calendar data; this row is an explainer.', '{}'::date[], 1, false),
  ('00000000-0000-0000-0000-000000000418', 'govardhan-puja', 'Govardhan Puja', '{}'::text[], 'A celebration of protection, community, gratitude, and Krishna in many Vaishnava settings.', 'Govardhan Puja is linked with stories of Krishna and the people of Vraja, with food offerings and local practices that express gratitude for land and sustenance.', 'Govardhan Puja is linked with stories of Krishna and the people of Vraja, with food offerings and local practices that express gratitude for land and sustenance.', 'Offer thanks for food, land, and those who care for it
Learn the version of the story your tradition tells
Share food without waste', '{"note":"The story, food forms, timing, and devotional emphasis differ among Vaishnava and regional communities."}'::jsonb, ARRAY['general']::text[], 'Calendar dates require reviewed calendar data; this row is an explainer.', '{}'::date[], 1, false),
  ('00000000-0000-0000-0000-000000000419', 'bhai-dooj', 'Bhai Dooj', ARRAY['Bhai Phota']::text[], 'A festival of sibling care, welcome, blessings, and mutual responsibility.', 'Bhai Dooj is observed through visits, food, gifts, and blessings, with related regional festivals carrying different names and stories.', 'Bhai Dooj is observed through visits, food, gifts, and blessings, with related regional festivals carrying different names and stories.', 'Contact a sibling or chosen family member with care
Offer a blessing without making the relationship transactional
Include people whose family structures differ from the traditional story', '{"note":"Names, rituals, foods, and the relationships celebrated vary across regions and households."}'::jsonb, ARRAY['general']::text[], 'Calendar dates require reviewed calendar data; this row is an explainer.', '{}'::date[], 1, false),
  ('00000000-0000-0000-0000-000000000420', 'ekadashi', 'Ekadashi', '{}'::text[], 'A recurring devotional observance marked by many communities through prayer, restraint, and remembrance.', 'Ekadashi is connected with the eleventh lunar day and is observed in diverse ways, especially in Vaishnava traditions. It may include fasting, but fasting is not appropriate for everyone.', 'Ekadashi is connected with the eleventh lunar day and is observed in diverse ways, especially in Vaishnava traditions. It may include fasting, but fasting is not appropriate for everyone.', 'Follow your family or teacher’s guidance rather than an internet rule
Choose prayer, study, or generosity if fasting is unsuitable
Seek qualified medical advice for health conditions or medication', '{"note":"Dates, foods, rules, names, and theological significance vary; never treat fasting as a test of spiritual worth."}'::jsonb, ARRAY['general']::text[], 'Calendar dates require reviewed calendar data; this row is an explainer.', '{}'::date[], 1, true),
  ('00000000-0000-0000-0000-000000000421', 'mahalaya-amavasya', 'Mahalaya Amavasya', '{}'::text[], 'A day associated in many communities with remembrance, ancestors, and transition into a festival season.', 'Mahalaya observances can include remembrance, recitation, offerings, and regional stories. Families may follow different customs or not observe the day.', 'Mahalaya observances can include remembrance, recitation, offerings, and regional stories. Families may follow different customs or not observe the day.', 'Ask family elders about the practice before adopting it
Remember loved ones through a safe and respectful act
Do not assume one ancestor practice applies to every household', '{"note":"The name, date, recitations, offerings, and relationship to Navaratri vary by region and tradition."}'::jsonb, ARRAY['general']::text[], 'Calendar dates require reviewed calendar data; this row is an explainer.', '{}'::date[], 1, false)
on conflict (slug) do update set
  name = excluded.name,
  name_variants = excluded.name_variants,
  short_description = excluded.short_description,
  full_story = excluded.full_story,
  meaning = excluded.meaning,
  home_observance = excluded.home_observance,
  regional_variations = excluded.regional_variations,
  traditions = excluded.traditions,
  tithi_rule = excluded.tithi_rule,
  upcoming_dates = excluded.upcoming_dates,
  duration_days = excluded.duration_days,
  is_premium = excluded.is_premium;

-- Down:
--   This migration upserts app-authored rows that may also exist in local
--   seed data, so an automatic delete would be destructive and could not
--   restore the previous copy. To reverse it, restore a pre-migration
--   database backup or the prior reviewed row versions, then remove only
--   rows whose deterministic IDs were introduced by this migration.
--   The generator must be rerun if the authored catalog changes.

